### ISSUE TITLE
Using advanced-ftp behind a proxy

### ISSUE THREAD

**Issue by cdacruz** [anversoft/node-red-contrib-advanced-ftp#1]
Hello,

I'm trying to implement advanced-ftp behind a proxy. Unfortunately I got a connection error.
Do you know how I solve it ?

Thanks a lot.

**Comment by anversoft** [comment]
Hi cdacruz,

unfortunately the library I used does not support connection via proxy. In the next few days I try to figure it out how to implement this function. Thanks for the tip!
