### ISSUE TITLE
How can I config server ip and username by msg input?

### ISSUE THREAD

**Issue by deryann** [anversoft/node-red-contrib-advanced-ftp#10]
Dear Sir:
   could we dynamic set ip, username, and pwd by msg in nodered?
   even from dashboard?

**Comment by anversoft** [comment]
Hello @deryann,

you can't right now but it's a simple line to modify, i'm working on it.
https://github.com/anversoft/node-red-contrib-advanced-ftp/blob/cf9d8bcaf0ccbd32813fe75e63ee597f1a1b4813/src/advanced-ftp.js#L603

and

https://github.com/anversoft/node-red-contrib-advanced-ftp/blob/cf9d8bcaf0ccbd32813fe75e63ee597f1a1b4813/src/advanced-ftp-logger.js#L759

**Comment by anversoft** [comment]
#11 Feature added
