### ISSUE TITLE
List not working as expected

### ISSUE THREAD

**Issue by mikehervas** [anversoft/node-red-contrib-advanced-ftp#2]
I'm trying to extract file size of a file in a folder from the FTP server.
When the filename is separated by space it will not get it properly.
These are the content of the folder:
![image](https://user-images.githubusercontent.com/66110685/83232981-9becc680-a1c0-11ea-87cd-0a5bd6c2853a.png)

I won't be able to get the file property if I supply the file name: horizon pump mpn search.csv
![image](https://user-images.githubusercontent.com/66110685/83233104-cb033800-a1c0-11ea-919e-9616155d70b7.png)

But if I tried to get the other one with the dash it will successfully return it: horizon-pump-mpn-search.csv
![image](https://user-images.githubusercontent.com/66110685/83233181-e9693380-a1c0-11ea-8e21-1b630ee5214e.png)

**Comment by anversoft** [comment]
Hi mikehervas,


I tried to recreate your same situation and it works for me. what version of advanced ftp are you using?

(it works even if I put the sign / in front of Test)

![image](https://user-images.githubusercontent.com/62706586/83536098-17b57e80-a4f3-11ea-9921-16275d9d48f3.png)
![image](https://user-images.githubusercontent.com/62706586/83535657-847c4900-a4f2-11ea-9e29-5d91994d674f.png)
![image](https://user-images.githubusercontent.com/62706586/83535982-f359a200-a4f2-11ea-8248-d43497e13b96.png)

**Comment by anversoft** [comment]
Also I tried to rename the Foo folder in "sc-lookup" because maybe the program interprets the - as an invalid character, but it works the same. if it doesn't work, try using LIST SAFE
