### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by seppelicous** [anversoft/node-red-contrib-advanced-ftp#3]
Hi,
I am the node to upload von file every 5 minutes on my ftp server.
After a few times I got an error because the number of clients connected to the server are reached. 
See the screenshot below.

Is there any issue with closing the active connection after uploading?
<img width="510" alt="Bildschirmfoto 2020-09-10 um 12 53 08" src="https://user-images.githubusercontent.com/34340436/92779662-8d5aa180-f3a2-11ea-9914-debd026de1dd.png">

**Comment by anversoft** [comment]
Hi seppelicous,

what version of advanced ftp are you using?

Each command ends with the client disconnecting from the server. Enable throw error in the options menu and tell me what error comes out in the nodered log.

Thank you!

**Comment by seppelicous** [comment]
Hi, your plugin is working perfect, is was my mistake. The flow sometimes receives hundreds of messages per second, ergo hundreds of file uploads in short time, due to an splitted array one node before.
I modified the flow and now it works perfect for 3 days now.

bets regards
