### ISSUE TITLE
Requesting support of recursive mkdir

### ISSUE THREAD

**Issue by danielnguyen** [anversoft/node-red-contrib-advanced-ftp#6]
**Current behavior:**
MKDIR fails when specifying a multi-level directory path that doesn't exist.

**Desired behavior:**
Ability to support recursive MKDIR to create missing directories in a given path.

**Suggestion:**
node-ftp seems to support a boolean parameter for the MKDIR operation: https://github.com/mscdex/node-ftp/blob/master/lib/connection.js#L674

Requesting to expose a simple `Recursive` flag in the node configuration to be passed into the MKDIR operation.

Thanks! (love this module btw, works great!)

**Comment by anversoft** [comment]
hi @danielnguyen , thanks for your support! In the next few days I will implement this function not only for MKDIR but also for RMDIR, also I want to implement the "useCompression" option for the data reception / transmission methods as well!

**Comment by anversoft** [comment]
Done, I've added the buttons inside the node configuration or you can send them through the payload with: msg.recursive = true or msg.useCompression = true.
If there are other problems please reopen this post.

**Comment by danielnguyen** [comment]
@anversoft thanks for such a quick response! Just tried it (via node config flag) and it works flawlessly :). This helps a ton, very much appreciated!
