### ISSUE TITLE
Multiple msg with uploads passed - but only one msg out

### ISSUE THREAD

**Issue by blackw1ng** [anversoft/node-red-contrib-advanced-ftp#7]
Hey, when i run the advanced-ftp node that receives two messages, i would expect, that two messages show up on the output... one per transfer.
![image](https://user-images.githubusercontent.com/5062706/122402462-cb15d780-cf7d-11eb-91ed-9d8fd187e4e5.png)
the surprising part is, that both files are actually uploaded - but the success message only happens once - and just for the _last_ message.
![image](https://user-images.githubusercontent.com/5062706/122402520-d8cb5d00-cf7d-11eb-8bc0-5c2a18f75c13.png)
seems like we want to send an outgoing message for every file regarding its status.

i am not a javascript expert - so maybe a trivial fix can be done. thanks.

**Comment by blackw1ng** [comment]
more interestingly, on three messages... i get two identical messages out :)
![image](https://user-images.githubusercontent.com/5062706/122403898-06fd6c80-cf7f-11eb-979d-7528ea5272ab.png)

**Comment by anversoft** [comment]
hey, can you send me your flow so i can check that it's alright? in the meantime try to take a look at this flow that I created for another problem, maybe it can help you.  #4

**Comment by anversoft** [comment]
The ftp library I used does not support multiple operations such as uploading multiple files and unfortunately I have not yet implemented an internal buffer to handle these requests. To work around your problem I suggest you use the code I created for the problem mentioned above and try to adapt it to yours.

**Comment by blackw1ng** [comment]
OK - thanks for the swift reply, the explanation and the solution approaches.
i will try to increase the watchdog time, and also try the buffer solution.

General outline around my challenge is:
- read / monitor an SMB folder for files
- upload all files that show up to an FTP
- for every file that was uploaded successfully, move it to a subfolder (keep state of what to upload)
(for the moving, i first remove a potentially existing previous file - latest one wins)

```
[
    {
        "id": "84ba54e3.b83858",
        "type": "inject",
        "z": "3338152c.01ea52",
        "name": "every 5 minutes",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 160,
        "y": 940,
        "wires": [
            [
                "ea65a797.09cf38"
            ]
        ]
    },
    {
        "id": "ea65a797.09cf38",
        "type": "SMB",
        "z": "3338152c.01ea52",
        "name": "List files in upload dir",
        "config": "dd0fc0d9.3754f8",
        "operation": "read-dir",
        "path": "",
        "path_new": "",
        "format": "string",
        "x": 240,
        "y": 1040,
        "wires": [
            [
                "a74a2396.d5897",
                "93c13ef4.886f7"
            ]
        ]
    },
    {
        "id": "a74a2396.d5897",
        "type": "debug",
        "z": "3338152c.01ea52",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 450,
        "y": 980,
        "wires": []
    },
    {
        "id": "701ce397.98527c",
        "type": "debug",
        "z": "3338152c.01ea52",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1030,
        "y": 1100,
        "wires": []
    },
    {
        "id": "283d8ee5.bfb642",
        "type": "function",
        "z": "3338152c.01ea52",
        "name": "set PUT filenames (split)",
        "func": "var filename = msg.payload\n\nif (filename !== \"transferred\")  {\n        msg.payload = {\n        \"Process Files\": {\n            \"Name\": \"File \" + filename + \" will be uploaded..\",\n        }};\n        msg.operation = \"PUT\";\n        msg.filename= filename;\n        msg.localFilename= filename;\n\n        node.send(msg);\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 630,
        "y": 1040,
        "wires": [
            [
                "5e942348.198e4c",
                "ec84c09a.f4c83"
            ]
        ]
    },
    {
        "id": "dd9808c6.f222b8",
        "type": "debug",
        "z": "3338152c.01ea52",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1530,
        "y": 1060,
        "wires": []
    },
    {
        "id": "ff3d07b2.12d338",
        "type": "SMB",
        "z": "3338152c.01ea52",
        "name": "",
        "config": "dd0fc0d9.3754f8",
        "operation": "rename",
        "path": "",
        "path_new": "",
        "format": "string",
        "x": 1510,
        "y": 900,
        "wires": [
            [
                "1cf9225f.d3864e"
            ]
        ]
    },
    {
        "id": "1cf9225f.d3864e",
        "type": "debug",
        "z": "3338152c.01ea52",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1630,
        "y": 780,
        "wires": []
    },
    {
        "id": "44f5d154.409",
        "type": "SMB",
        "z": "3338152c.01ea52",
        "name": "remove dest file",
        "config": "dd0fc0d9.3754f8",
        "operation": "unlink",
        "path": "",
        "path_new": "",
        "format": "string",
        "x": 1100,
        "y": 880,
        "wires": [
            [
                "80c4f4ca.eb00b8",
                "dd9808c6.f222b8"
            ]
        ]
    },
    {
        "id": "ee9a3ece.9cfca",
        "type": "function",
        "z": "3338152c.01ea52",
        "name": "Move successful transfers",
        "func": "var failure_msg = { payload:\"Unable to move data...\" };\nvar i = 0;\nvar new_msg = { payload:\"\" } ;\n\n\nif (msg.payload === \"PUT operation successful.\") {\n    new_msg.payload = {\n        \"Process Files\": {\n        \"Name\": \"File \" + msg.filename + \" to be moved.\",\n    }};\n    new_msg.filename=\"transferred\\\\\"+msg.filename;\n    new_msg.orig_filename = msg.filename\n    \n    node.send(new_msg);\n}\nelse {\n    return failure_msg;\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 1090,
        "y": 1000,
        "wires": [
            [
                "44f5d154.409",
                "3c980bf9.f68764"
            ]
        ]
    },
    {
        "id": "80c4f4ca.eb00b8",
        "type": "function",
        "z": "3338152c.01ea52",
        "name": "Move successful transfers",
        "func": "var failure_msg = { payload:\"Unable to move data...\" };\nvar i = 0;\nvar new_msg = { payload:\"\" } ;\n\n\nif (msg.payload.length !== 0) {\n    new_msg.payload = {\n        \"Process Files\": {\n        \"Name\": \"File \" + msg.filename + \" to be moved.\",\n    }};\n    new_msg.new_filename=msg.filename;\n    new_msg.filename = msg.orig_filename\n    \n    node.send(new_msg);\n}\nelse {\n    return failure_msg;\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 1290,
        "y": 780,
        "wires": [
            [
                "26610d50.d8caf2",
                "ff3d07b2.12d338"
            ]
        ]
    },
    {
        "id": "3c980bf9.f68764",
        "type": "debug",
        "z": "3338152c.01ea52",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1270,
        "y": 1100,
        "wires": []
    },
    {
        "id": "26610d50.d8caf2",
        "type": "debug",
        "z": "3338152c.01ea52",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1470,
        "y": 680,
        "wires": []
    },
    {
        "id": "93c13ef4.886f7",
        "type": "split",
        "z": "3338152c.01ea52",
        "name": "",
        "splt": "\\n",
        "spltType": "str",
        "arraySplt": "1",
        "arraySpltType": "len",
        "stream": false,
        "addname": "",
        "x": 430,
        "y": 1040,
        "wires": [
            [
                "283d8ee5.bfb642"
            ]
        ]
    },
    {
        "id": "ec84c09a.f4c83",
        "type": "debug",
        "z": "3338152c.01ea52",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 870,
        "y": 1100,
        "wires": []
    },
    {
        "id": "5e942348.198e4c",
        "type": "advanced-ftp",
        "z": "3338152c.01ea52",
        "ftp": "91b51b40.35e9a8",
        "operation": "put",
        "dataType": "binary",
        "filename": "",
        "localFilename": "",
        "workingDir": "",
        "oldPath": "",
        "newPath": "",
        "command": "",
        "recursive": false,
        "useCompression": false,
        "throwError": false,
        "showError": true,
        "name": "",
        "x": 870,
        "y": 1040,
        "wires": [
            [
                "701ce397.98527c",
                "ee9a3ece.9cfca"
            ]
        ]
    },
    {
        "id": "dd0fc0d9.3754f8",
        "type": "smb config",
        "z": "",
        "name": "",
        "share": "\\\\172.18.1.64\\Data",
        "domain": ""
    },
    {
        "id": "91b51b40.35e9a8",
        "type": "advanced-ftp-config",
        "z": "",
        "host": "FTPHOST",
        "port": "21",
        "secure": true,
        "secureOptions": "",
        "user": "test",
        "connTimeout": "1000",
        "pasvTimeout": "1000",
        "keepalive": "10000",
        "name": "stg secure"
    }
]
```

**Comment by blackw1ng** [comment]
Thanks @anversoft for the hints - the queue indeed works. 🎉 
However now i get a weird error from the watchdog node, that i need to track down :)
![image](https://user-images.githubusercontent.com/5062706/122530695-0c11f880-d01f-11eb-8b78-0869911abf5c.png)

**Comment by anversoft** [comment]
That's strange... try this

`[
    {
        "id": "4c35e90f.f97bb8",
        "type": "tab",
        "label": "Flow 3",
        "disabled": false,
        "info": ""
    },
    {
        "id": "2322bbc5.55c6c4",
        "type": "function",
        "z": "4c35e90f.f97bb8",
        "name": "FTP Buffer",
        "func": "var contextName = \"file_buffer\"; //Context Buffer Name\nvar fb = context.get(contextName) || []; //Get the context files names array, if it doesn't exist, create it.\n\nif(msg.topic === \"Flush\"){ //Flush Requested, recreate the buffer\n fb = [];\n context.set(contextName, fb);\n return null;\n}\n\nif(!msg.hasOwnProperty(\"filename\") || !msg.hasOwnProperty(\"localFilename\")){ //Check if msg contains the ftp properties. \n node.warn(\"msg does not contain filename or localFilename property\");\n return null; \n}\n\nvar ftpMessage = { //Create the ftp msg object\n filename : msg.filename,\n localFilename : msg.localFilename,\n}\n\nif(msg.topic === \"Request\"){ //Request Command, add the new request to the buffer\n \n let firstRequest = fb.length > 0 ? false : true; //If the buffer is empty, send the first element of the array\n fb.push(ftpMessage);\n \n if(firstRequest){\n ftpMessage = fb[0];\n node.send(ftpMessage);\n }\n}\n\nif(msg.topic === \"Completed\" && fb.length > 0){ //Completed Command, a file download is complete\n\n let index = -1;\n \n for(let file in fb){\n\n if(fb[file].filename == ftpMessage.filename && \n fb[file].localFilename == ftpMessage.localFilename){\n \n index = file;\n break;\n }\n }\n \n if (index > -1) { //If the index is found, remove the request from the buffer\n fb.splice(index, 1);\n }\n \n if(fb.length > 0){ //Send the fist element of the array\n ftpMessage = fb[0];\n node.send(ftpMessage);\n }\n}\n\ncontext.set(contextName, fb); //Update the buffer\n\n",
        "outputs": 1,
        "noerr": 0,
        "x": 810,
        "y": 220,
        "wires": [
            [
                "802aac54.e48d9",
                "17fdd538.b72f2b",
                "366cac0.6fc25d4"
            ]
        ]
    },
    {
        "id": "ad277ad4.3479d8",
        "type": "function",
        "z": "4c35e90f.f97bb8",
        "name": "set PUT filenames (split)",
        "func": "var filename = msg.payload\n\nif (filename !== \"transferred\")  {\n        msg.payload = {\n        \"Process Files\": {\n            \"Name\": \"File \" + filename + \" will be uploaded..\",\n        }};\n        msg.operation = \"PUT\";\n        msg.filename= filename;\n        msg.localFilename= filename;\n        msg.topic = \"Request\"\n\n        node.send(msg);\n}",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 570,
        "y": 220,
        "wires": [
            [
                "2322bbc5.55c6c4"
            ]
        ]
    },
    {
        "id": "8c84c47c.a92c38",
        "type": "inject",
        "z": "4c35e90f.f97bb8",
        "name": "Manual Flush",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "Flush",
        "payload": "a",
        "payloadType": "str",
        "x": 130,
        "y": 360,
        "wires": [
            [
                "2322bbc5.55c6c4"
            ]
        ]
    },
    {
        "id": "7bfa3a61.e19ce4",
        "type": "change",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "Completed",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1190,
        "y": 220,
        "wires": [
            [
                "4bacc921.bdb528",
                "c3ed89ed.a75388"
            ]
        ]
    },
    {
        "id": "4bacc921.bdb528",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "Download Completed",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1442.5,
        "y": 179,
        "wires": []
    },
    {
        "id": "c3ed89ed.a75388",
        "type": "link out",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "links": [
            "ceb7cbdd.3b5618"
        ],
        "x": 1357,
        "y": 219,
        "wires": []
    },
    {
        "id": "ceb7cbdd.3b5618",
        "type": "link in",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "links": [
            "c3ed89ed.a75388",
            "7d2196e1.5d0f98"
        ],
        "x": 655,
        "y": 160,
        "wires": [
            [
                "2322bbc5.55c6c4"
            ]
        ]
    },
    {
        "id": "802aac54.e48d9",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "To PUT node",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 993,
        "y": 171,
        "wires": []
    },
    {
        "id": "17fdd538.b72f2b",
        "type": "trigger",
        "z": "4c35e90f.f97bb8",
        "name": "Watchdog",
        "op1": "",
        "op2": "",
        "op1type": "nul",
        "op2type": "payl",
        "duration": "2",
        "extend": true,
        "overrideDelay": false,
        "units": "min",
        "reset": "",
        "bytopic": "all",
        "topic": "topic",
        "outputs": 1,
        "x": 801,
        "y": 271,
        "wires": [
            [
                "a7df59c7.b1ffb8"
            ]
        ]
    },
    {
        "id": "a7df59c7.b1ffb8",
        "type": "change",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "Flush",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 811,
        "y": 319,
        "wires": [
            [
                "7d2196e1.5d0f98",
                "4721f7cb.0a2fe8"
            ]
        ]
    },
    {
        "id": "7d2196e1.5d0f98",
        "type": "link out",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "links": [
            "ceb7cbdd.3b5618"
        ],
        "x": 923,
        "y": 319,
        "wires": []
    },
    {
        "id": "4721f7cb.0a2fe8",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "Flush if the Completed msg doesn't arrive",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 903,
        "y": 361,
        "wires": []
    },
    {
        "id": "366cac0.6fc25d4",
        "type": "advanced-ftp",
        "z": "4c35e90f.f97bb8",
        "ftp": "91b51b40.35e9a8",
        "operation": "put",
        "dataType": "binary",
        "filename": "",
        "localFilename": "",
        "workingDir": "",
        "oldPath": "",
        "newPath": "",
        "command": "",
        "recursive": false,
        "useCompression": false,
        "throwError": false,
        "showError": true,
        "name": "",
        "x": 1010,
        "y": 220,
        "wires": [
            [
                "7bfa3a61.e19ce4",
                "c417f6df.dfeda"
            ]
        ]
    },
    {
        "id": "94e44327.1799c",
        "type": "inject",
        "z": "4c35e90f.f97bb8",
        "name": "every 5 minutes",
        "props": [
            {
                "p": "payload",
                "v": "",
                "vt": "date"
            },
            {
                "p": "topic",
                "v": "",
                "vt": "string"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 100,
        "y": 120,
        "wires": [
            [
                "dbc74ec.d4dc7b"
            ]
        ]
    },
    {
        "id": "dbc74ec.d4dc7b",
        "type": "SMB",
        "z": "4c35e90f.f97bb8",
        "name": "List files in upload dir",
        "config": "dd0fc0d9.3754f8",
        "operation": "read-dir",
        "path": "",
        "path_new": "",
        "format": "string",
        "x": 180,
        "y": 220,
        "wires": [
            [
                "3faab1e.bc47ece",
                "6b7e5270.8cbe34"
            ]
        ]
    },
    {
        "id": "3faab1e.bc47ece",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 390,
        "y": 160,
        "wires": []
    },
    {
        "id": "6b7e5270.8cbe34",
        "type": "split",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "splt": "\\n",
        "spltType": "str",
        "arraySplt": "1",
        "arraySpltType": "len",
        "stream": false,
        "addname": "",
        "x": 370,
        "y": 220,
        "wires": [
            [
                "ad277ad4.3479d8"
            ]
        ]
    },
    {
        "id": "717104df.abe19c",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1190,
        "y": 680,
        "wires": []
    },
    {
        "id": "350c8430.3b6ae4",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1690,
        "y": 640,
        "wires": []
    },
    {
        "id": "3336282a.a135b",
        "type": "SMB",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "config": "dd0fc0d9.3754f8",
        "operation": "rename",
        "path": "",
        "path_new": "",
        "format": "string",
        "x": 1670,
        "y": 480,
        "wires": [
            [
                "e969fe07.934878"
            ]
        ]
    },
    {
        "id": "e969fe07.934878",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1790,
        "y": 360,
        "wires": []
    },
    {
        "id": "d015bbdf.258ef",
        "type": "SMB",
        "z": "4c35e90f.f97bb8",
        "name": "remove dest file",
        "config": "dd0fc0d9.3754f8",
        "operation": "unlink",
        "path": "",
        "path_new": "",
        "format": "string",
        "x": 1260,
        "y": 460,
        "wires": [
            [
                "557ef6f.9667b08",
                "350c8430.3b6ae4"
            ]
        ]
    },
    {
        "id": "c417f6df.dfeda",
        "type": "function",
        "z": "4c35e90f.f97bb8",
        "name": "Move successful transfers",
        "func": "var failure_msg = { payload:\"Unable to move data...\" };\nvar i = 0;\nvar new_msg = { payload:\"\" } ;\n\n\nif (msg.payload === \"PUT operation successful.\") {\n    new_msg.payload = {\n        \"Process Files\": {\n        \"Name\": \"File \" + msg.filename + \" to be moved.\",\n    }};\n    new_msg.filename=\"transferred\\\\\"+msg.filename;\n    new_msg.orig_filename = msg.filename\n    \n    node.send(new_msg);\n}\nelse {\n    return failure_msg;\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 1250,
        "y": 580,
        "wires": [
            [
                "d015bbdf.258ef",
                "d1e5f439.3fa85"
            ]
        ]
    },
    {
        "id": "557ef6f.9667b08",
        "type": "function",
        "z": "4c35e90f.f97bb8",
        "name": "Move successful transfers",
        "func": "var failure_msg = { payload:\"Unable to move data...\" };\nvar i = 0;\nvar new_msg = { payload:\"\" } ;\n\n\nif (msg.payload.length !== 0) {\n    new_msg.payload = {\n        \"Process Files\": {\n        \"Name\": \"File \" + msg.filename + \" to be moved.\",\n    }};\n    new_msg.new_filename=msg.filename;\n    new_msg.filename = msg.orig_filename\n    \n    node.send(new_msg);\n}\nelse {\n    return failure_msg;\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 1450,
        "y": 360,
        "wires": [
            [
                "96172db9.c04378",
                "3336282a.a135b"
            ]
        ]
    },
    {
        "id": "d1e5f439.3fa85",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1430,
        "y": 680,
        "wires": []
    },
    {
        "id": "96172db9.c04378",
        "type": "debug",
        "z": "4c35e90f.f97bb8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1650,
        "y": 320,
        "wires": []
    },
    {
        "id": "ead1ff8b.10629",
        "type": "comment",
        "z": "4c35e90f.f97bb8",
        "name": "WATCHDOG DESCRIPTION",
        "info": "The purpose of the watchdog is to avoid that if the file is not loaded and / or the ftp server does not send any response then it stop the upload of the remaining files, you can always intercept the Flush command to save the unsent files and try again later.",
        "x": 860,
        "y": 120,
        "wires": []
    },
    {
        "id": "91b51b40.35e9a8",
        "type": "advanced-ftp-config",
        "host": "FTPHOST",
        "port": "21",
        "secure": true,
        "secureOptions": "",
        "user": "test",
        "connTimeout": "1000",
        "pasvTimeout": "1000",
        "keepalive": "10000",
        "name": "stg secure"
    },
    {
        "id": "dd0fc0d9.3754f8",
        "type": "smb config",
        "name": "",
        "share": "\\\\172.18.1.64\\Data",
        "domain": ""
    }
]`

**Comment by blackw1ng** [comment]
Wow thanks - works like a charm 🎉  awesome, thanks - in case you are in Munich at some point, hit me up, i will buy you a beer :)

**Comment by anversoft** [comment]
Aahah I'll take it thanks a lot! I took a look at your profile and I have to give you my sincere compliments for contributing to projects like the Mars drone. If you are in Franciacorta I will offer you a glass of wine!

If you need help just ask ;)
