### ISSUE TITLE
DateTime

### ISSUE THREAD

**Issue by fioronileo** [anversoft/node-red-contrib-advanced-ftp#8]
List ftp : date is ok, time is always 00:00:00

{"type":"-","name":"P0000206.jpg","sticky":false,"rights":{"user":"rwx","group":"rx","other":"rx"},"acl":false,"owner":"tsuser","group":"data","size":101465,"date":"2019-11-06T00:00:00.000Z"}

**Comment by anversoft** [comment]
Hi fioronileo!

unfortunately, it is a problem with the FTP client library used (as you can see from this snippet the result is returned without alteration). 

https://github.com/anversoft/node-red-contrib-advanced-ftp/blob/cf9d8bcaf0ccbd32813fe75e63ee597f1a1b4813/src/advanced-ftp.js#L332-L335

If you need the precise datetime you can use the LAST MOD command and pass as a parameter the name of the folder / file you need.
